### ISSUE TITLE
Ic2 compatibility issue when using a mining laser to kill other players /entities

### ISSUE THREAD

**Issue by TechStack** [DemoXinMC/MoreEnchants#4]
Hello sadly we had to remove your mod from my server because of an incompatiblity when a mining laser kills another player. 
as you can see from the error and stack strace below it occurs because the IC2 mining laser class cannot be cast to an Entityarrow even though the damage source is arrow.

Anyway like I said I've already removed the mod for my purposes but i wanted to let you know of the issue if you want to fix it.

Thanks ,
Tech
stack trace / error :

java.lang.ClassCastException: ic2.core.item.tool.EntityMiningLaser cannot be cast to net.minecraft.entity.projectile.EntityArrow
        at com.demoxin.minecraft.moreenchants.Item_Charm.HandleSharpness(Item_Charm.java:147)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_224_Item_Charm_HandleSharpness_LivingHurtEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:285)
        at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1081)
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:783)
        at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1035)
        at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:496)
        at ic2.core.item.tool.EntityMiningLaser.func_70071_h_(EntityMiningLaser.java:229)
        at net.minecraft.world.World.func_72866_a(World.java:2019)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:659)
        at net.minecraft.world.World.func_72870_g(World.java:1983)
        at net.minecraft.world.World.func_72939_s(World.java:1836)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:500)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:621)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:326)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:531)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:670)

**Comment by DemoXinMC** [comment]
Fixed in the next version. The code is already in to correct the clash.

**Comment by TechStack** [comment]
OK cool, for reference we were using the MoreEnchants-MC1.7-1.3.1.jar version.

**Comment by DemoXinMC** [comment]
It's a pretty simple fix, just need to add in an extra check.  Disabling charms will fix the issue temporarily as well until I can get the next version out.
